Feature: As an admin I want to be able to manage 

Background: Admin User added to coursiz  
Given I am on "users/sign_up"
When I have added my name "Commander" 
And have added email "admin@coursiz.herokuapp.com" 
And have added password "Admin.coursiz!"
And have added password conformation "Admin.coursiz!"
And selected year "Senior"
And selected major "Computer"
And I have pressed "Sign up"
Then a new account should be created 
And I should see "Welcome! You have signed up successfully."
When I click link "Logout"
When I selected id "1" Admin from the database



Scenario: Valid Signin with Admin

Given I am on "users/sign_in"
And have added email "admin@coursiz.herokuapp.com" 
And have added password "Admin.coursiz!"
And I have pressed "Sign in"
And I should see "Signed in successfully."
And I should see "Manage"

Scenario: Make another user Admin

Given I am on "users/sign_up"
When I have added my name "Big John" 
And have added email "gunnar-mills@uiowa.edu" 
And have added password "bigjohn1234"
And have added password conformation "bigjohn1234" 
And selected year "Senior"
And selected major "Computer"
And I have pressed "Sign up"
And I should see "Welcome! You have signed up successfully."
When I click link "Logout"
Given I am on "users/sign_in"
And have added email "admin@coursiz.herokuapp.com" 
And have added password "Admin.coursiz!"
And I have pressed "Sign in"
And I should see "Signed in successfully."
When I click link "Admin"
When I selected id "2" Admin from the database
When I click link "Logout"
Given I am on "users/sign_in"
And have added email "gunnar-mills@uiowa.edu" 
And have added password "bigjohn1234"
And I have pressed "Sign in"
Then I should see "Signed in successfully."
And I should see "Manage"

Scenario: Delete other user 

Given I am on "users/sign_up"
When I have added my name "Big John" 
And have added email "gunnar-mills@uiowa.edu" 
And have added password "bigjohn1234"
And have added password conformation "bigjohn1234" 
And selected year "Senior"
And selected major "Computer"
And I have pressed "Sign up"
And I should see "Welcome! You have signed up successfully."
When I click link "Logout"
Given I am on "users/sign_in"
And have added email "admin@coursiz.herokuapp.com" 
And have added password "Admin.coursiz!"
And I have pressed "Sign in"
And I should see "Signed in successfully."
When I click link "Admin"
When I click link "Delete user"



Scenario: Add New Category 

Given I am on "users/sign_in"
And have added email "admin@coursiz.herokuapp.com" 
And have added password "Admin.coursiz!"
And I have pressed "Sign in"
And I should see "Signed in successfully."
And I should see "Manage"
When I click link "Manage"
And have added name "Selt"
And I have pressed "Add Category"
And I should see "Selt was added successfully" 
And have added name "Digital Design"
And I have pressed "Add Category"
When I click link "Quizzes by Category"
Then I should see "Selt"
And I should see "Digital Design"

Scenario: Attempt to add same quiz

Given I am on "users/sign_in"
And have added email "admin@coursiz.herokuapp.com" 
And have added password "Admin.coursiz!"
And I have pressed "Sign in"
And I should see "Signed in successfully."
And I should see "Manage"
When I click link "Manage"
And have added name "Selt"
And I have pressed "Add Category"
And I should see "Selt was added successfully" 
And have added name "Selt"
And I have pressed "Add Category"
And I should see "Please review the problems below:" 



Scenario: Add question 

Given I am on "users/sign_in"
And have added email "admin@coursiz.herokuapp.com" 
And have added password "Admin.coursiz!"
And I have pressed "Sign in"
And I should see "Signed in successfully."
And I should see "Manage"
When I click link "Manage"
And have added name "Selt"
And I have pressed "Add Category"
And I should see "Selt"
And selected category "Selt"
And selected progress "Middle"
And I have entered Question "What type of typing is Ruby?"
And I have entered Answer "Dynamic"
And I have entered FalseAnswer1 "Static typing"
And I have entered FalseAnswer2 "Static and Dynamic typing"
And I have entered FalseAnswer3 "Neither Static or Dynamic typing"
And I have pressed "Submit Question"
Then I should see "The question was successfully created!"

Scenario: Leave Category blank on Question 

Given I am on "users/sign_in"
And have added email "admin@coursiz.herokuapp.com" 
And have added password "Admin.coursiz!"
And I have pressed "Sign in"
And I should see "Signed in successfully."
And I should see "Manage"
When I click link "Manage"
And have added name "Selt"
And I have pressed "Add Category"
And I should see "Selt"
And selected progress "Middle"
And I have entered Question "What type of typing is Ruby?"
And I have entered Answer "Dynamic"
And I have entered FalseAnswer1 "Static typing"
And I have entered FalseAnswer2 "Static and Dynamic typing"
And I have entered FalseAnswer3 "Neither Static or Dynamic typing"
And I have pressed "Submit Question"
Then I should see "Please review the problems below:"

Scenario: Leave Progress blank on Question 

Given I am on "users/sign_in"
And have added email "admin@coursiz.herokuapp.com" 
And have added password "Admin.coursiz!"
And I have pressed "Sign in"
And I should see "Signed in successfully."
And I should see "Manage"
When I click link "Manage"
And have added name "Selt"
And I have pressed "Add Category"
And I should see "Selt"
And selected category "Selt"
And I have entered Question "What type of typing is Ruby?"
And I have entered Answer "Dynamic"
And I have entered FalseAnswer1 "Static typing"
And I have entered FalseAnswer2 "Static and Dynamic typing"
And I have entered FalseAnswer3 "Neither Static or Dynamic typing"
And I have pressed "Submit Question"
Then I should see "Please review the problems below:"

Scenario: Leave question blank on Question 

Given I am on "users/sign_in"
And have added email "admin@coursiz.herokuapp.com" 
And have added password "Admin.coursiz!"
And I have pressed "Sign in"
And I should see "Signed in successfully."
And I should see "Manage"
When I click link "Manage"
And have added name "Selt"
And I have pressed "Add Category"
And I should see "Selt"
And selected category "Selt"
And selected progress "Middle"
And I have entered Answer "Dynamic"
And I have entered FalseAnswer1 "Static typing"
And I have entered FalseAnswer2 "Static and Dynamic typing"
And I have entered FalseAnswer3 "Neither Static or Dynamic typing"
And I have pressed "Submit Question"
Then I should see "Please review the problems below:"

Scenario: Leave answer blank on Question 

Given I am on "users/sign_in"
And have added email "admin@coursiz.herokuapp.com" 
And have added password "Admin.coursiz!"
And I have pressed "Sign in"
And I should see "Signed in successfully."
And I should see "Manage"
When I click link "Manage"
And have added name "Selt"
And I have pressed "Add Category"
And I should see "Selt"
And selected category "Selt"
And selected progress "Middle"
And I have entered Question "What type of typing is Ruby?"
And I have entered FalseAnswer1 "Static typing"
And I have entered FalseAnswer2 "Static and Dynamic typing"
And I have entered FalseAnswer3 "Neither Static or Dynamic typing"
And I have pressed "Submit Question"
Then I should see "Please review the problems below:"

Scenario: Leave false answer blank on Question 

Given I am on "users/sign_in"
And have added email "admin@coursiz.herokuapp.com" 
And have added password "Admin.coursiz!"
And I have pressed "Sign in"
And I should see "Signed in successfully."
And I should see "Manage"
When I click link "Manage"
And have added name "Selt"
And I have pressed "Add Category"
And I should see "Selt"
And selected category "Selt"
And selected progress "Middle"
And I have entered Question "What type of typing is Ruby?"
And I have entered Answer "Dynamic"
And I have entered FalseAnswer1 "Static typing"
And I have pressed "Submit Question"
Then I should see "Please review the problems below:"
